spring:
  #hibernate
  jpa:
    database: h2
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    platform: h2

logging:
  level:
    root: info
    org:
      springframework:
        orm:
          jpa: debug
        transaction:
          interceptor: TRACE
